name: Deploy to Coolify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl --request GET \
            --url "https://dev.7rb.nl/api/v1/deploy?uuid=b8f8kmbenoly2e9ase1b3joj&force=false" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            --fail
